name: Depoly
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install package
        run: |
          sudo apt-get install -y libvips
          which vips

      - name: Set up go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.16.1'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Go mod
        run: |
          go mod tidy
      - name: Build
        run: |
          CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -v -o release/linux/amd64/err .

      - name: Upload
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_ADDR }}
          key: ${{ secrets.VPS_KEY }}
          username: ${{ secrets.VPS_USR }}
          port: ${{ secrets.VPS_PORT }}
          source: "release/linux/amd64/err"
          target: "~"

      - name: Run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_ADDR }}
          key: ${{ secrets.VPS_KEY }}
          username: ${{ secrets.VPS_USR }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            sudo -S service err restart << EOF
            ${{ secrets.VPS_PWD }}
            EOF
          
